# Generated by Django 3.2.7 on 2021-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='editprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('userqualification', models.CharField(max_length=50)),
                ('userdesignation', models.CharField(max_length=50)),
                ('mobileno', models.PositiveIntegerField()),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('companydescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='occupation',
            field=models.CharField(choices=[('Home Maker', 'Home Maker'), ('Government Employee', 'Government Employee'), ('Artist', 'Artist'), ('Social Worker', 'Social Worker'), ('Freelencer', 'Freelencer'), ('Designer', 'Designer'), ('Enterpreneur', 'Enterpreneur'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='qualification',
            field=models.CharField(choices=[('10th/12th', '10th/12th'), ('Under_Graduate', 'Under_Graduate'), ('Post_Graduate', 'Post_Graduate'), ('PHD', 'PHD')], max_length=50),
        ),
    ]
