# Generated by Django 3.2.7 on 2021-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211012_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='companydescription',
            field=models.TextField(),
        ),
    ]
