# Generated by Django 3.2.7 on 2021-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211017_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='editprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
