# Generated by Django 3.2.7 on 2021-10-17 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_auto_20211017_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='editprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
