# Generated by Django 3.2.7 on 2021-10-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20211017_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companydescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobileno',
            field=models.PositiveIntegerField(default=1111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userdesignation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='userqualification',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
