# Generated by Django 3.2.7 on 2021-10-28 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0014_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('ptype', models.CharField(max_length=200)),
                ('pcategory', models.CharField(max_length=50)),
                ('best_before', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('packaging_Details', models.TextField()),
                ('preferred_consumer', models.CharField(max_length=100)),
                ('About_product', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
