# Generated by Django 3.2.7 on 2021-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20211028_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='productimg/'),
        ),
    ]
